version: "2"
services:
  web:
    image: aizamjj/reservation-form_web:firsttry
    command: bash -c "npm run seed & npm start"
    ports:
      - "80:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"